version: "2"

services: 
  hello-container: 
    container_name: hello
    build: .
    image: hello-container:local
    # entrypoint: tail -f /dev/null
    environment:
      - PORT=3000
    ports:
      - 3000:3000