apiVersion: v1
kind: Service
metadata:
  name: hello-container
spec:
  selector:
    app: hello-container
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-container
  template:
    metadata:
      labels:
        app: hello-container
    spec:
      containers:
      - name: hello-container
        image: martinnirtl/hello-container:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
