const pino = require('pino');
const express = require('express');

const port = process.env.PORT || 3000;

const logger = pino({
  level: 'debug',
  prettyPrint: process.env.NODE_ENV !== 'production',
  formatters: {
    level: label => ({ level: label }),
  },
});

const app = express();

const log = (req, _res, next) => {
  logger.debug(`handling request on ${req.path}`);

  next();
};

app.get('/', log, (_req, res) => res.send(`Hi there!<br>Welcome to hello-container!<br><br>This response was generated by ${process.env.CONTAINER_NAME || 'hello-container'} [namespace: ${process.env.NAMESPACE_NAME || '-'}] on ${process.env.HOST || 'localhost'}.`));

app.get('/hello', log, (_req, res) => res.send('hello world'));

app.get('/hello/:name', log, (req, res) => res.send(`hello ${req.params.name}`));

app.get('/hello/:name/:greeting', log, (req, res) => res.send(`${req.params.greeting} ${req.params.name}`));

app.listen(port, () => logger.info(`app listening on port ${port}`));